server:
  port: 8090

  # JSP 재실행 설정
  servlet:
    jsp:
      init-parameters:
        development: true

spring:
  # JSP 설정
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # H2 DB Connection
  datasource:
    url: jdbc:h2:mem:mooddiary;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  #schema sql init
  sql:
    init:
      mode: always

  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.moodcalendar.domain
  configuration:
    map-underscore-to-camel-case: true
